name: Windows Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=_install

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: cmake --build build --target install --config Release
